### ISSUE TITLE
Registry API: Support sort property in ListApisRequest

### ISSUE THREAD

**Issue by michaelyara** [apigee/registry#343] opened 2021-10-12 18:27 UTC
At the moment the `ListApisRequest` supports pagination and filtering, however if the endpoint is to be used to supply data for most common paginated usecases (i.e. UI tables) the request should also sort by properties of `Api` to provide proper pagination results.

This limitation requires that any UI that wishes to sort and paginate APIs must fetch all apis in the registry and filter/sort/paginate manually.

**Comment by timburks** [comment] 2022-01-04 19:31
See also #54

**Comment by timburks** [comment] 2022-09-01 18:42
Closed as a duplicate of #54, which is now resolved and closed.

**Closed by timburks** 2022-09-01 18:42 UTC
Labels: enhancement
